CoffeeShop/Models/UserInformationViewModel.cs
using CoffeeShopDTO;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CoffeeShopWebApp.Models
{
	public class UserInformationViewModel
	{
		public int Id { get; set; }
		[DisplayName("First Name")]
		[Required]
		public string FirstName { get; set; }
		[DisplayName("Last Name")]
		[Required]
		public string LastName { get; set; }
		[Required]
		public string Email { get; set; }
		[Required]
		public string Password { get; set; }

		public static UserInformationViewModel ViewModelMapper(UserInformation userDTO)
		{
			return new UserInformationViewModel
			{
				Id = userDTO.Id,
				FirstName = userDTO.FirstName,
				LastName= userDTO.LastName,
				Email = userDTO.Email,
				Password = userDTO.Password,
			};
		}

		//send to the dB as an update (id is required)
		public static UserInformation UserDtoMapperForUpdate(IFormCollection collection)
		{
			return new UserInformation
			{
				Id = int.Parse(collection["Id"]),
				FirstName = collection["FirstName"],
				LastName = collection["LastName"],
				Email = collection["Email"],
				Password = collection["Password"]
			};
		}

		//send to the db as a create (it is generated in the db)
		public static UserInformation UserDtoMapperForCreate(IFormCollection collection)
		{
			return new UserInformation
			{
				FirstName = collection["FirstName"],
				LastName = collection["LastName"],
				Email = collection["Email"],
				Password = collection["Password"]
			};
		}



	}
}

CoffeeShop/Controllers/UserInformationController.cs
using CoffeeShopDomain;
using CoffeeShopDTO;
using CoffeeShop.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using CoffeeShopWebApp.Models;

namespace CoffeeShopWebApp.Controllers
{
	public class UserInformationController : Controller	
	{
		private UserInformationInteractor _interactor;

		public UserInformationController()
		{
			_interactor = new UserInformationInteractor();
		}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Welcome(int userId)
		{
			_interactor.GetUserIfExists(userId, out var user);
			return View(user);
		}



		// GET: UserInformationController
		public IActionResult Index()
		{
			List<UserInformationViewModel> items = new List<UserInformationViewModel>();

			List<UserInformation> dbItems = _interactor.GetAllUsers();
			foreach (UserInformation item in dbItems)
			{
				UserInformationViewModel viewItem = UserInformationViewModel.ViewModelMapper(item);
				items.Add(viewItem);
			}

			return View(items);
		}

		// GET: UserInformationController/Details/5
		public IActionResult Details(int id)
		{
			if (_interactor.GetUserIfExists(id, out UserInformation dbItem))
			{
				UserInformationViewModel viewItem = UserInformationViewModel.ViewModelMapper(dbItem);
				return View(viewItem);
			}
			else
			{
				return RedirectToAction(nameof(Index));
			}
		}

		// GET: UserInformationController/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: UserInformationController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(IFormCollection collection)
		{
			try
			{
				UserInformation userToAdd = UserInformationViewModel.UserDtoMapperForCreate(collection);
				_interactor.AddNewUser(userToAdd);
				var userToView = UserInformationViewModel.ViewModelMapper(userToAdd);
				return RedirectToAction("Welcome");
			}
			catch (Exception ex)
			{
				return View();
			}
		}

		// GET: UserInformationController/Edit/5
		public IActionResult Edit(int id)
		{
			if (_interactor.GetUserIfExists(id, out UserInformation dbItem))
			{
				UserInformationViewModel viewItem = UserInformationViewModel.ViewModelMapper(dbItem);
				return View(viewItem);
			}
			else
			{
				return RedirectToAction(nameof(Index));
			}
		}

		// POST: UserInformationController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(int id, IFormCollection collection)
		{
			try
			{
				UserInformation itemToUpdate = UserInformationViewModel.UserDtoMapperForUpdate(collection);
				_interactor.UpdateUser(itemToUpdate);
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}

		}

		// GET: UserInformationController/Delete/5
		public IActionResult Delete(int id)
		{
			if (_interactor.GetUserIfExists(id, out UserInformation dbItem))
			{
				UserInformationViewModel viewItem = UserInformationViewModel.ViewModelMapper(dbItem);
				return View(viewItem);
			}
			else
			{
				return RedirectToAction(nameof(Index));
			}
		}

		// POST: UserInformationController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
				_interactor.DeleteUser(id);
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

CoffeeShop/Views/UserInformation/Create.cshtml
@model CoffeeShopWebApp.Models.UserInformationViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>User Registration</h1>

<h4>Please Submit The Completed Form To Register</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
 
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" type="password"/>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoffeeShop/Views/UserInformation/Delete.cshtml
@model CoffeeShopWebApp.Models.UserInformationViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserInformationViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CoffeeShop/Views/UserInformation/Edit.cshtml
@model CoffeeShopWebApp.Models.UserInformationViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>UserInformationViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoffeeShop/Views/UserInformation/Index.cshtml
@model IEnumerable<CoffeeShopWebApp.Models.UserInformationViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Current Registered Users</h1>

<p>
    <button type="button" class="btn btn-primary btn-lg btn-block" onclick="location.href='@Url.Action("Create", "UserInformation")'">Register New User</button>
    
</p>
<table class="table">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |                
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

CoffeeShop/Views/UserInformation/Welcome.cshtml
@model CoffeeShopWebApp.Models.UserInformationViewModel

@{
    ViewData["Title"] = "Welcome";
}

<h1>Welcome</h1>

<div>
    <h4>UserInformationViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>